---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
implicit:
  - При переключении языка все элементы сайта должны переводиться в соответствии с выбранным языком
  - При переключении языка должна изменяться валюта, в которой отображается стоимость товаров в соответствии с выбранным языком
  - При выборе категории товаров пользователь должен иметь возможность отменить его без перезагрузки страницы
  - В корзине у пользователя должна быть возможность удалять полностью количество товара одним нажатием
